version: '3.3'

services:
    samba:
        image: awlnx/samba-timemachine:latest
        ports:
            - 10445:445
        volumes:
            - /backups/timemachine:/backups:rw
        restart: unless-stopped
        tty: true
