name: ci
 
on:
 push:
   branches: main
 
jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     - name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Build and push
       uses: docker/build-push-action@v2
       with:
         context: .
         file: Dockerfile
         platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
         push: true
         tags: |
           awlnx/samba-timemachine:latest
